agendamentos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # django admin
    path('admin/', admin.site.urls),

    # user management
    path('accounts/', include('users.urls')),

    # local
    path('', include('pages.urls', namespace='pages')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView, name='home'),
    path('month:<int:month>/', views.HomePageView, name='home'),

    path('new-scheduling/', views.NewScheduling, name='new_scheduling'),
    path('update-scheduling/<int:id>/', views.UpdateScheduling, name='update_scheduling'),
    path('delete-scheduling/<int:id>/', views.DeleteScheduling, name='delete_scheduling'),
]

schedules/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # django admin
    path('admin/', admin.site.urls),

    # user management
    path('accounts/', include('users.urls')),

    # local
    path('', include('pages.urls', namespace='pages')),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_view


urlpatterns = [
    # user management (allauth)
    path('', include('allauth.urls')),
]

pages/models.py
from django.db import models
from django.utils import timezone
from users.models import User


class Scheduling(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    scheduling_date = models.DateTimeField()
    scheduling_done = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.scheduling_done = 'Will be done'
        super(Scheduling, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    """
    To create a new schedule, you need to import the module "datetime" this way:
    
        import datetime
        from pages.models import Scheduling
        
        date = datetime.datetime(<year>,<mouth>,<day>,<hour><minutes>,<seconds>,<milliseconds>)
        new_scheduling = Scheduling(nome="name", scheduling_date=date)
        new_scheduling.save()
    """

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

pages/forms.py
from django import forms
from .models import Scheduling
from django.core.exceptions import ValidationError
from .models import Scheduling
import datetime


class DateTimeInput(forms.DateTimeInput):
    input_type = 'text'


class NewScheduling(forms.ModelForm):
    class Meta:
        model = Scheduling
        fields = ['name', 'scheduling_date', 'phone_number']
        widgets = {'scheduling_date': DateTimeInput(attrs={'type': 'datetime-local'})}
        help_texts = {'phone_number': 'DDD plus the phone number'}

    def clean_scheduling_date(self):
        data = self.cleaned_data['scheduling_date']

        schedules = Scheduling.objects.filter(scheduling_date=data)

        if schedules.first() is not None:
            raise ValidationError('Already have an scheduling for this date')

        elif data < datetime.datetime.now():
            raise ValidationError('Invalid date')

        return data

    def clean_phone_number(self):
        phone = self.cleaned_data['phone_number']

        if phone == '':
            return phone

        elif len(phone) == 11 or len(phone) == 10:
            for character in phone:
                if character.isdigit():
                    pass
                else:
                    raise ValidationError('enter a valid phone number')

        else:
            raise ValidationError('enter a valid phone number')

        return phone

pages/views.py
from django.shortcuts import redirect, render
from pages.models import *
from .forms import NewScheduling as NewSchedulingForm
import datetime, calendar
from .calendarFunction import calendarFunction


def HomePageView(request, month=datetime.date.today().month):
    user = request.user

    print(month)

    if user.is_authenticated:
        # atualizando 'scheduling_date' para done
        Scheduling.objects.filter(scheduling_date__lte=timezone.now(), user=user).update(scheduling_done='done')

        # verificando se existe algum agendamento
        schedules = Scheduling.objects.filter(user=user)
        calendar_values = calendarFunction(month)

        context = {
            'schedules': schedules,
            'calendar_values': calendar_values
        }

    else:
        context = {}

    return render(request, 'home.html', context=context)


def NewScheduling(request):
    user = request.user

    if user.is_authenticated:
        if request.method == 'POST':
            form = NewSchedulingForm(request.POST)

            if form.is_valid():
                scheduling_date = form.cleaned_data['scheduling_date']
                name = form.cleaned_data['name']
                phone_number = form.cleaned_data['phone_number']

                new_schedule = Scheduling(
                    user=user,
                    name=name,
                    scheduling_date=scheduling_date,
                    phone_number=phone_number,
                )

                new_schedule.save()

                return redirect('/')

        else:
            form = NewSchedulingForm()
    else:
        return redirect('/')

    return render(request, 'Schedules/new_scheduling.html', {'form': form})


def UpdateScheduling(request, id):
    
    return render(request, 'Schedules/update_scheduling.html', {'form': form})


def DeleteScheduling(request, id):
    context = {}
    return render(request, 'Schedules/delete_scheduling.html', context=context)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/Schedules/delete_scheduling.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="Create schedule">
</form>
{% endblock %}

templates/Schedules/new_scheduling.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}New scheduling{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="Create schedule">
</form>
{% endblock %}

templates/Schedules/update_scheduling.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="Create schedule">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Schedules - {% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Schedules</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:new_scheduling' %}">New Scheduling</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Exit</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
<h3>Olá {{ user.username }}!</h3>
<h1>Your schedules</h1>

        {% if schedules %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Date</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>

            {% for scheduling in schedules %}
        <tr>
            <td>{{scheduling.id}}</td>
            <td>{{scheduling.name}}</td>
            <td>{{scheduling.scheduling_date}}</td>
            <td>{{scheduling.scheduling_done}}</td>
        </tr>

            {% endfor %}
    </tbody>
</table>

        {% else %}
<p>No appointments found, you can create <a href="{% url 'pages:new_scheduling' %}">clicking here</a></p>

        {% endif %}

    {% else %}
        Cadastre-se ou faça login.

    {% endif %}
{% endblock %}